# Cleaning, manipulation and unification of Datasets

### 1) Complete dataset of inorganic chemistry of water surfaces

#### 1.1) File upload

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import display, Math, Latex
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
# First look at the dataset structure

In [4]:
# River samples up to 1998 from regions A to D:
rivers1=pd.read_excel('Rivers up to 1998 (A-D).xlsx')
rivers1.head()

,SAMPLE STATION/POINT ID\nAND SAMPLING DATE,Unnamed: 1,Unnamed: 2,Unnamed: 3,ELECTRICAL CONDUCTIVITY\n\nNOTE: Variables in bold represent original data from DWA,Unnamed: 5,Unnamed: 6,Unnamed: 7,MAJOR IONS CHEMICAL COMPOSITION\n\nNOTE: Variables in bold represent original data from DWA,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,TOTAL DISSOLVED SOLIDS,Unnamed: 23,Unnamed: 24,CHARGE BALANCE CALCULATION,Unnamed: 26,Unnamed: 27,MOLAR CONCENTRATIONS IN 10-3 MOL PER LITER (MMOL/L),Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,IONIC STRENGTH,SA WATER CHARACTERISATION PARAMETERS,Unnamed: 44,Unnamed: 45,SODIUM ADSORPTION RATIO,Unnamed: 47
0,NaN,NaN,NaN,NaN,mS/m,mS/cm,mS/cm,%,NaN,mg/L,mg/L,mg/L,mg/L,mg/L,mg/L,mg/L,mg/L,mg/L,mg/L CaCO3,mg/L,mg/L,mg/L,mg/L,%,(mg/L)/(mS/cm),meq/L,meq/L,%,mmol/L,mmol/L,mmol/L,mmol/L,mmol/L,mmol/L,mmol/L,mmol/L,mmol/L,mmol/L,mmol/L,mmol/L,mmol/L,mmol/L,NaN,NaN,NaN,NaN,NaN,NaN
1,SAMPLE\nSTATION ID,POINT ID,DATE,YEAR,EC,EC,EC (calc.),dEC,PH,TDS,NaN,MG,CA,F,CL,NO2+NO3,SO4,PO4,TAL,SI,K,NH4,TDS (calc.),dTDS,TDS/EC (mS/cm),Sz+,Sz-,Charge Balance,[NA],[MG],[CA],[F],[CL],[NO3],[SO4],[PO4],[SI],[K],[NH4],[TAL],[HCO3],[CO3],I,[HCO3]+2[CO3],2[SO4],[CL],SAR,adj. SAR
2,A1H001Q01,NaN,1989-03-03 00:00:00,1989,45.4,454,379.349,-16.443,7.7,354,1.6,24.9,47.9,0.09,4.6,1.04,1.7,0.005,220.1,5.54,0.21,0.05,314.051,-11.2851,0.933178,4.51612,4.58863,-0.796312,0.0695652,1.02469,1.19451,0.00473684,0.129577,0.0167742,0.0176899,5.26316e-05,0.197153,0.00537084,0.00277778,2.201,4.38,0.0110021,0.00680043,96.388,0.774691,2.83728,0.0466975,0.0536643
3,A1H001Q01,NaN,1989-06-02 00:00:00,1989,44.6,446,397.909,-10.7828,7.7,362,2.8,28,47.4,0.1,6.5,1.09,5.3,0.008,218.7,6.07,0.4,0.04,323.328,-10.6829,0.909756,4.80281,4.6905,1.18306,0.121739,1.15226,1.18204,0.00526316,0.183099,0.0175806,0.0551509,8.42105e-05,0.216014,0.0102302,0.00222222,2.187,4.35214,0.0109321,0.0071473,93.7138,2.36324,3.92292,0.0796803,0.0905088
4,A1H001Q01,NaN,1989-09-02 00:00:00,1989,43.8,438,381.056,-13.001,8.24,353,2.1,28.1,41.4,0.07,6.2,1.03,2.8,0.011,219.2,5.55,0.27,0.03,313.088,-11.3065,0.926374,4.47747,4.63757,-1.75637,0.0913043,1.15638,1.03242,0.00368421,0.174648,0.0166129,0.0291363,0.000115789,0.197509,0.00690537,0.00166667,2.192,4.30894,0.0375293,0.00681333,94.9551,1.26215,3.78278,0.0617147,0.0688726